---
- hosts: primary
  tasks:
  - name: allow ntp through firewall
    shell: firewall-cmd --add-service=ntp --permanent

  - name: firewall reload
    shell: firewall-cmd --reload

  - name: Make sure Chrony is started up
    service: name=chronyd state=started enabled=yes
    tags: chrony

- hosts: secondary
  tasks:
  - name: set timezone
    shell: timedatectl set-timezone America/New_York

  - name: Install NTP
    yum: name=ntp state=installed
    tags: ntp

  - name: Copy over the NTP configuration
    template: src=./template/ntp.j2 dest=/etc/ntp.conf
    copy: src=/tmp/ntp.conf dest=/etc/ntp.conf
    notify:
    - restart ntpd
    tags: ntp

  - name: Make sure NTP is stopped
    service: name=ntpd state=stopped enabled=yes
    tags: ntp

  - name: Sync time initialy
    shell: ntpdate 0.centos.pool.ntp.org
    tags: ntp

  - name: Make sure NTP is started up
    service: name=ntpd state=restarted enabled=yes
    tags: ntp

  - name: Sync hwclock
    shell: hwclock -w
    tags: ntp

  handlers:
  - name: restart ntpd
    service: name=ntpd state=restarted

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add sudoers users to root group
    user:
      name=dba_rw
      password='p@ssw0rd' 
      groups=wheels
      append=yes
      state=present
      createhome=yes
      shell=/bin/bash
